version: '3'
services:
  discovery-server:
    build:
      dockerfile: Dockerfile
      context: ./eureka/
    ports:
      - "8761:8761"
  exchange-server:
    build: ./exchange/
    depends_on:
      - discovery-server
    ports:
    - "8086:8086"
  cart-server:
    build: ./cart/
    depends_on:
      - exchange-server
      - discovery-server
      - redis
    ports:
    - "8085:8085"
  redis:
    image: 'redis:latest'
    ports:
    - "6379:6379"